# This file is machine-generated - editing it directly is not advised

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[Bzip2_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "92463331a641b19fc3baa427e0b76cdbd54dc05d"
uuid = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
version = "1.0.6+1"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[DocStringExtensions]]
deps = ["LibGit2", "Markdown", "Pkg", "Test"]
git-tree-sha1 = "88bb0edb352b16608036faadcc071adda068582a"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.8.1"

[[Expat_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "e1b4190be75ba8d03ce2bec3a6cfc7a939c713ea"
uuid = "2e619515-83b5-522b-bb60-26c02a35a201"
version = "2.2.7+0"

[[FreeType2_jll]]
deps = ["Bzip2_jll", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "8e290780d75bc0f676548c3bb84c153f83d14bdc"
uuid = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
version = "2.10.1+1"

[[GLEW_jll]]
deps = ["Libdl", "Libglvnd_jll", "Pkg", "X11_jll", "Xorg_libXi_jll"]
git-tree-sha1 = "cbc0778a866389f895e2101bd18ee23bc7b5182f"
uuid = "bde7f898-03f7-559e-8810-194d950ce600"
version = "2.1.0+2"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[JpegTurbo_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "b007cedc10bb017cdae3af0062fe4dd29b483c70"
uuid = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
version = "2.0.1+0"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Libgcrypt_jll]]
deps = ["Libdl", "Libgpg_error_jll", "Pkg"]
git-tree-sha1 = "9592d031aac2566fb5cf9eeb28e2d7b05db9b9ef"
uuid = "d4300ac3-e22c-5743-9152-c294e39db1e4"
version = "1.8.5+0"

[[Libglvnd_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll", "Xorg_libXext_jll"]
git-tree-sha1 = "30a990af9ce535bcba54d1f23f071a7e714f861e"
uuid = "7e76a0d4-f3c7-5321-8279-8d96eeed0f29"
version = "1.3.0+1"

[[Libgpg_error_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "3332d872d131a6ee88f10f20d7d131ece886c424"
uuid = "7add5ba3-2f88-524e-9cd5-f83b8a55f7b8"
version = "1.36.0+0"

[[Libiconv_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "802f5b23c846cb4ed568cae0bfb0ce0d2ba1926d"
uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531"
version = "1.16.0+1"

[[Libtiff_jll]]
deps = ["JpegTurbo_jll", "Libdl", "Pkg", "Zlib_jll", "Zstd_jll"]
git-tree-sha1 = "6cab365abd0108b45e1cbd234223152d88647742"
uuid = "89763e89-9b03-5906-acba-b20f662cd828"
version = "4.0.10+0"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Lz4_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "e1a93171a400d4578193eaa39edd2d3f5db08fb6"
uuid = "5ced341a-0733-55b8-9ab6-a4889d929147"
version = "1.9.2+0"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Pkg]]
deps = ["Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "Test", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[VTKMinimal_jll]]
deps = ["Expat_jll", "FreeType2_jll", "GLEW_jll", "JpegTurbo_jll", "Libdl", "Libtiff_jll", "Lz4_jll", "Pkg", "XZ_jll", "Xorg_libICE_jll", "Xorg_libSM_jll", "Xorg_libXi_jll", "Xorg_libXt_jll", "Xorg_libXtst_jll", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "7a085eb12d5088b6b140d5db9ee5e829d40dc226"
uuid = "529833da-d7f1-5821-aee9-3785d4589272"
version = "8.2.0+1"

[[X11_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "dfadaea7e3fa9120b06824b634342fc6cba58109"
uuid = "546b0b6d-9ca3-5ba2-8705-1bc1841d8479"
version = "1.6.8+5"

[[XML2_jll]]
deps = ["Libdl", "Libiconv_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "ed5603a695aefe3e9e404fc7b052e02cc72cfab6"
uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
version = "2.9.9+1"

[[XSLT_jll]]
deps = ["Libdl", "Libgcrypt_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "77d0086a876532cb4fae005d4c9ecc8236dcdceb"
uuid = "aed1982a-8fda-507f-9586-7b0439959a61"
version = "1.1.33+0"

[[XZ_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "8df1fd97689336692e81f91ad95fd59eb4123406"
uuid = "ffd25f8a-64ca-5728-b0f7-c24cf3aae800"
version = "5.2.4+3"

[[Xorg_fixesproto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "101dcd548d6021b8d3cdaeb66c65c0d85faf1bcb"
uuid = "cf2f014d-5496-555f-b295-889ac9dfddaa"
version = "5.0.0+0"

[[Xorg_inputproto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "a941739b553f589cd264dc16fdeaf5300af30f51"
uuid = "84d6cd60-beca-5f49-93c5-789031781a2d"
version = "2.3.2+0"

[[Xorg_libICE_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "fe11b7fd8423a4f44437fd1a07dfb7c6efc15b27"
uuid = "f67eecfb-183a-506d-b269-f58e52b52d7c"
version = "1.0.10+0"

[[Xorg_libSM_jll]]
deps = ["Libdl", "Pkg", "Xorg_libICE_jll"]
git-tree-sha1 = "4a9d9e4c180e1e8119b5ffc224a7b59d3a7f7e18"
uuid = "c834827a-8449-5923-a945-d239c165b7dd"
version = "1.2.3+0"

[[Xorg_libX11_jll]]
deps = ["Libdl", "Pkg", "Xorg_libxcb_jll", "Xorg_xtrans_jll"]
git-tree-sha1 = "b04e87c6b8a7f80aa9f8239dd5d23bb3324728fa"
uuid = "4f6342f7-b3d2-589e-9d20-edeb45f2b2bc"
version = "1.6.9+1"

[[Xorg_libXau_jll]]
deps = ["Libdl", "Pkg", "Xorg_xproto_jll"]
git-tree-sha1 = "e47d249f952653b7f1b0d3d7d7ed40d081d7096b"
uuid = "0c0b7dd1-d40b-584c-a123-a41640f87eec"
version = "1.0.9+1"

[[Xorg_libXdmcp_jll]]
deps = ["Libdl", "Pkg", "Xorg_util_macros_jll", "Xorg_xproto_jll"]
git-tree-sha1 = "f477af835cd12647d253b9c7a86e768b14d04fff"
uuid = "a3789734-cfe1-5b06-b2d0-1dd0d9d62d05"
version = "1.1.3+1"

[[Xorg_libXext_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll", "Xorg_util_macros_jll", "Xorg_xextproto_jll"]
git-tree-sha1 = "43ff58a4d17cc9710bfadccaa7249f2e44c4b20b"
uuid = "1082639a-0dae-5f34-9b06-72781eeb8cb3"
version = "1.3.4+1"

[[Xorg_libXfixes_jll]]
deps = ["Libdl", "Pkg", "Xorg_fixesproto_jll", "Xorg_libX11_jll", "Xorg_util_macros_jll"]
git-tree-sha1 = "ff358baf2b575c149d2115a6a1a2ca772868ee97"
uuid = "d091e8ba-531a-589c-9de9-94069b037ed8"
version = "5.0.3+1"

[[Xorg_libXi_jll]]
deps = ["Libdl", "Pkg", "Xorg_inputproto_jll", "Xorg_libXext_jll", "Xorg_libXfixes_jll", "Xorg_util_macros_jll"]
git-tree-sha1 = "4ea59b9d391a81553d24d68b15dd191e8fe39afc"
uuid = "a51aa0fd-4e3c-5386-b890-e753decda492"
version = "1.7.10+1"

[[Xorg_libXt_jll]]
deps = ["Libdl", "Pkg", "Xorg_libSM_jll", "Xorg_libX11_jll"]
git-tree-sha1 = "cbc802be2b2d4eeaf44cdb00083fe5fbe7ba78be"
uuid = "28c4a263-0105-5ca0-9a8c-f4f6b89a1dd4"
version = "1.2.0+0"

[[Xorg_libXtst_jll]]
deps = ["Libdl", "Pkg", "Xorg_inputproto_jll", "Xorg_libXext_jll", "Xorg_libXfixes_jll", "Xorg_libXi_jll", "Xorg_recordproto_jll", "Xorg_util_macros_jll"]
git-tree-sha1 = "81a154ce423d2346d80b5a700acbfb9f60dfd733"
uuid = "b6f176f1-7aea-5357-ad67-1d3e565ea1c6"
version = "1.2.3+1"

[[Xorg_libpthread_stubs_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "5c2806e6e08b093ca2071e53602651f4a5e079da"
uuid = "14d82f49-176c-5ed1-bb49-ad3f5cbd8c74"
version = "0.1.0+0"

[[Xorg_libxcb_jll]]
deps = ["Libdl", "Pkg", "XSLT_jll", "Xorg_libXau_jll", "Xorg_libXdmcp_jll", "Xorg_libpthread_stubs_jll", "Xorg_util_macros_jll", "Xorg_xcb_proto_jll"]
git-tree-sha1 = "6f5c3e3d1e3201613f38c4042ca79521e3c0bb97"
uuid = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b"
version = "1.13.0+1"

[[Xorg_recordproto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "0192d9bc3f2bfdd90191e055c412c3fd3faf4b1d"
uuid = "a7b44dc7-5846-51fe-a1cd-6b242f0ec0a2"
version = "1.14.2+0"

[[Xorg_util_macros_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "a99f6275c9b2a9862d2cc4e714aad806c2daecc1"
uuid = "7c09cfe3-afe2-5798-bcc9-d6b7fecfdca5"
version = "1.19.2+0"

[[Xorg_xcb_proto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "1506cde098df4b6dedcc082bf9386a5808ee6dea"
uuid = "c2e9c405-c068-5e7b-9b35-084fd074cae4"
version = "1.13.0+0"

[[Xorg_xextproto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "0a1da65671cfc3b20926081b668c7dd098dd9c76"
uuid = "d13bc2ba-d276-5c6f-8a1c-29ed04aab5d0"
version = "7.3.0+0"

[[Xorg_xproto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "fdb0d8bae06762e24dade427e7914d199cdd721e"
uuid = "46797783-dccc-5433-be59-056c4bde8513"
version = "7.0.31+0"

[[Xorg_xtrans_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "b18f01c3b50be7bde08be131934112db3137f28b"
uuid = "c5fb5394-a638-5e4d-96e5-b29de1b5cf10"
version = "1.4.0+0"

[[Zlib_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "fd36a6739e256527287c5444960d0266712cd49e"
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.2.11+8"

[[Zstd_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "aa97e3e240e86010da61254b0045b7175ead0659"
uuid = "3161d3a3-bdf6-5164-811a-617609db77b4"
version = "1.4.4+0"

[[libpng_jll]]
deps = ["Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "30c6baf453f2603faedb846289f955d307ddf3b2"
uuid = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
version = "1.6.37+2"

[[vtkfig_jll]]
deps = ["Libdl", "Pkg", "VTKMinimal_jll"]
git-tree-sha1 = "ef2393ac1f4b3f70571b413e0ffc8123074aa545"
uuid = "2bcdf5c0-6329-11ea-0b83-f5d1b57ecfa1"
version = "0.22.0+0"
