name = "VTKView"
uuid = "63b67fce-66f7-11ea-1808-1361d8c55bf4"
authors = ["Juergen Fuhrmann <juergen.fuhrmann@wias-berlin.de>"]
version = "0.1.3"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
vtkfig_jll = "10287013-a584-5a38-a29a-42553acd0316"

[compat]
DocStringExtensions = "^0.8"
ForwardDiff = "^0.10"
julia = "^1.3"
